### ISSUE TITLE
Why ARM hardware acceleration is guarded by nightly

### ISSUE THREAD

**Issue by lizhanhui** [zowens/crc32c#47]
Is there anything that blocks ARM hardware acceleration feature  from being stable?

Will it be better to guard it using a feature?

**Comment by zowens** [comment]
The crc32c intrinsics are still nightly only: https://doc.rust-lang.org/nightly/core/arch/aarch64/index.html

**Comment by jbg** [comment]
This crate currently does not build on nightly on aarch64:

```
error[E0635]: unknown feature `stdarch_arm_crc32`
  --> /home/app/.cargo/registry/src/index.crates.io-6f17d22bba15001f/crc32c-0.6.5/src/lib.rs:23:60
   |
23 | #![cfg_attr(all(target_arch = "aarch64", nightly), feature(stdarch_arm_crc32))]
   |                                                            ^^^^^^^^^^^^^^^^^

For more information about this error, try `rustc --explain E0635`.
error: could not compile `crc32c` (lib) due to 1 previous error
```

**Comment by shikhar** [comment]
Looks like `stdarch_arm_crc32` is stable in Rust 1.80!

See also https://github.com/srijs/rust-crc32fast/pull/36

**Comment by zowens** [comment]
This is no longer guarded on nightly! If you are on the latest nightly or have rust 1.80 you should be good to go.
