### ISSUE TITLE
Rust 1.76: unsupported output in build script of `crc32c v0.6.6`: `cargo::rerun-if-changed=build.rs`

### ISSUE THREAD

**Issue by ryzhyk** [zowens/crc32c#67]
This line
https://github.com/zowens/crc32c/blob/938eada661e7192491efbd3cc3e40104cfa9ab77/build.rs#L186
unfortunately breaks Rust 1.76 (and probably earlier versions):

```
error: unsupported output in build script of `crc32c v0.6.6`: `cargo::rerun-if-changed=build.rs`
Found a `cargo::key=value` build directive which is reserved for future use.
Either change the directive to `cargo:key=value` syntax (note the single `:`) or upgrade your version of Rust.
See https://doc.rust-lang.org/cargo/reference/build-scripts.html#outputs-of-the-build-script for more information about build script outputs.
warning: build failed, waiting for other jobs to finish...

```

**Comment by zowens** [comment]
Yikes, I'll pull that out.

**Comment by zowens** [comment]
Try 0.6.7 and let me know if that fixes the issue

**Comment by ryzhyk** [comment]
There's one more:
```
error: unsupported output in build script of `crc32c v0.6.7`: `cargo::rustc-check-cfg=cfg(armsimd)`
Found a `cargo::key=value` build directive which is reserved for future use.
Either change the directive to `cargo:key=value` syntax (note the single `:`) or upgrade your version of Rust.
See https://doc.rust-lang.org/cargo/reference/build-scripts.html#outputs-of-the-build-script for more information about build script outputs.
```

**Comment by jayvdb** [comment]
This is still breaking macos builds even using latest rust stable.

**Comment by jayvdb** [comment]
Adding the following to your Cargo.toml will workaround this problem
```toml
[patch.crates-io]
# Workaround for https://github.com/zowens/crc32c/issues/67
crc32c = { git = "https://github.com/jayvdb/crc32c", branch = "crc-i67" }
```

**Comment by jbg** [comment]
@zowens It wasn't necessary to remove the output completely, just to make it a single colon `:` instead of double colon `::`. The single colon `:` is compatible with current and past Rust versions, while the double colon `::` is only compatible with rustc 1.77 and later.

The fix seems to have been reverted in master and no new release has been made, so there is still quite widespread breakage caused by this crate.

**Comment by zowens** [comment]
@jbg I _think_ it's now fixed in master (and v0.6.8 of the crate) to compile properly on rust >= 1.76... but if you find that's not the case let me know or open a PR with the fix you think will work properly. I'm a bit dizzy with the changes here on the cargo buildscript formats (these seem like breaking changes on Cargo).

**Comment by jbg** [comment]
I'll test and report back! They're not breaking changes because the old format continues to work - `cargo:` (with a single colon) works with both old and new rustc.

**Comment by zowens** [comment]
Ah that's fair, we could have stuck to the single colon.

**Comment by yukkit** [comment]
hi

**Comment by yukkit** [comment]
> 你好，我也遇到了类似的问题，具体如下：
> 
> ```
> cargo +nightly udeps --all-targets --all-features --quiet
> error: unsupported output in build script of `crc32c v0.6.8`: `cargo::rustc-check-cfg=cfg(armsimd)`
> Found a `cargo::key=value` build directive which is reserved for future use.
> Either change the directive to `cargo:key=value` syntax (note the single `:`) or upgrade your version of Rust.
> See https://doc.rust-lang.org/cargo/reference/build-scripts.html#outputs-of-the-build-script for more information about build script outputs.
> make: *** [udeps_check] Error 101
>  ✘ yukkit@mac  ~/VCWorkspace/c722   main ±✚  cargo +nightly  --version
> cargo 1.82.0-nightly (0d8d22f83 2024-08-08)
>  yukkit@mac  ~/VCWorkspace/c722   main ±✚  
> ```

cargo 1.82.0-nightly (0d8d22f83 2024-08-08)
release: 1.82.0-nightly
commit-hash: 0d8d22f83b066503f6b2b755925197e959e58b4f
commit-date: 2024-08-08
host: aarch64-apple-darwin
libgit2: 1.8.1 (sys:0.19.0 vendored)
libcurl: 8.7.1 (sys:0.4.74+curl-8.9.0 system ssl:(SecureTransport) LibreSSL/3.3.6)
ssl: OpenSSL 3.3.1 4 Jun 2024
os: Mac OS 14.6.1 [64-bit]
