### ISSUE TITLE
Broken build on nightly

### ISSUE THREAD

**Issue by morenol** [zowens/crc32c#72]
error: unsupported output in build script of `crc32c v0.6.8`: `cargo::rustc-check-cfg=cfg(armsimd)`
Found a `cargo::key=value` build directive which is reserved for future use.
Either change the directive to `cargo:key=value` syntax (note the single `:`) or upgrade your version of Rust.

**Comment by zowens** [comment]
You might be using an older nightly version. The crate compiles on my machine with this version of nightly:

```
$ rustc --version
rustc 1.82.0-nightly (8b3870784 2024-08-07)
```

**Comment by morenol** [comment]
Yes,my bad I had an old version of `cargo udeps`
